package application.controller;

<<<<<<< HEAD
import application.model.question.CustomeQuestion;
=======
import application.model.Question.CustomeQuestion;
import application.model.Question.CustomeQuestionSuite;
>>>>>>> 9e4fc4fdcf73a878e467970a4a6019addb77ff33
import application.tableModel.TableList;
import javafx.fxml.FXML;

import com.jfoenix.controls.JFXButton;

import javafx.scene.control.Label;

import javafx.scene.input.MouseEvent;

public class CustomTestPageController {
	@FXML
	private Label _question;
	@FXML
	private JFXButton _record;
	@FXML
	private JFXButton _next;
	@FXML
	private JFXButton _return;
	@FXML
	private Label _message;
	@FXML
	private Label _level;
	@FXML
	private JFXButton _play;

	private static TableList _selectedQS;

	private String _id;

	private boolean _isPublic;

<<<<<<< HEAD
=======
	private CustomeQuestionSuite _qs;

>>>>>>> 9e4fc4fdcf73a878e467970a4a6019addb77ff33
	private CustomeQuestion _q;

	@FXML
	public void initialize() {
		_selectedQS = CustomDoPageController.getSelected();
		_id = _selectedQS.getName();
<<<<<<< HEAD
=======
		_qs = new CustomeQuestionSuite(_id, _selectedQS.getPublic());
>>>>>>> 9e4fc4fdcf73a878e467970a4a6019addb77ff33
	}


	// Event Listener on JFXButton[#_record].onMouseClicked
	@FXML
	public void handlePressRecord(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on JFXButton[#_next].onMouseClicked
	@FXML
	public void handlePressNext(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on JFXButton[#_return].onMouseClicked
	@FXML
	public void handlePressReturn(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#_play].onMouseClicked
	@FXML
	public void handlePressPlay(MouseEvent event) {
		// TODO Autogenerated
	}
}
