package application.controller;

import javafx.fxml.FXML;

import com.jfoenix.controls.JFXButton;

import javafx.scene.control.ListView;

import javafx.scene.input.MouseEvent;

public class CustomDoPageController {
	@FXML
	private ListView _allList;
	@FXML
	private ListView _publicList;
	@FXML
	private ListView _privateList;
	@FXML
	private ListView _questionList;
	@FXML
	private JFXButton _do;
	@FXML
	private JFXButton _edit;
	@FXML
	private JFXButton _delete;

	// Event Listener on JFXButton[#_do].onMouseClicked
	@FXML
	public void handlePressDo(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#_edit].onMouseClicked
	@FXML
	public void handlePressEdit(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#_delete].onMouseClicked
	@FXML
	public void handlePressDelete(MouseEvent event) {
		// TODO Autogenerated
	}
}
