package application.controller;

import application.tableModel.TableList;
import javafx.fxml.FXML;

import javafx.scene.input.MouseEvent;

public class CustomTestPageController extends TestPageController {

	private static TableList _selectedQS;

	private String _id;

	private boolean _isPublic;



	@FXML
	public void initialize() {
		_selectedQS = CustomDoPageController.getSelected();
		_id = _selectedQS.getName();
		//_qs = new CustomeQuestionSuite(_id, _selectedQS.getPublic());
	}


	// Event Listener on JFXButton[#_next].onMouseClicked
	@FXML
	public void handlePressNext(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on JFXButton[#_return].onMouseClicked
	@FXML
	public void handlePressReturn(MouseEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void collectResult() {

	}
}
