package application.view;

import javafx.fxml.FXML;

import com.jfoenix.controls.JFXButton;

import javafx.scene.control.Label;

import javafx.scene.input.MouseEvent;

public class CustomTestPageController {
	@FXML
	private Label _question;
	@FXML
	private JFXButton _record;
	@FXML
	private JFXButton _next;
	@FXML
	private JFXButton _return;
	@FXML
	private Label _message;
	@FXML
	private Label _level;
	@FXML
	private JFXButton _play;

	// Event Listener on JFXButton[#_record].onMouseClicked
	@FXML
	public void handlePressButton(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#_next].onMouseClicked
	@FXML
	public void handlePressNext(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#_return].onMouseClicked
	@FXML
	public void handlePressReturn(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#_play].onMouseClicked
	@FXML
	public void handlePressPlay(MouseEvent event) {
		// TODO Autogenerated
	}
}
